---
- name: testing
  hosts: localhost
  tasks:
      - name: simple echo test
        command:
          cmd: "echo 'DIFFERENT TEST'"

      - name: debugging from Shell exansion
        debug:
          msg: "The IP address is: {{ IP_ADDR }}"

      - name: debugging from Ansible
        debug:
          msg: "The IP address is: {{ lookup('env','PUBLIC_IP') }}"

      - name: debugging from Ansible, facts
        debug:
          var: ansible_facts
