---
- name: testing
  hosts: localhost
  tasks:
    - name: debugging, node_1
      debug:
        msg: "Node 1's IP address is: {{ NODE_1_IP_ADDR }}"

    - name: debugging, node_2
      debug:
        msg: "Node 2's IP address is: {{ NODE_2_IP_ADDR }}"

    - name: debugging, node_3
      debug:
        msg: "Node 3's IP address is: {{ NODE_3_IP_ADDR }}"

- name: Configure Docker for EC2 Nodes
  hosts: "{{ NODE_1_IP_ADDR }} {{ NODE_2_IP_ADDR }} {{ NODE_3_IP_ADDR }}"
  tasks:
    - name: ping to test connectivity
      ping:

