---
- name: testing
  hosts: localhost
  tasks:
      - name: simple echo test
        command:
          cmd: "echo 'DIFFERENT TEST'"

      - name: debugging
        debug:
          msg: "The IP address is: {{ IP_ADDR }}"
