---
- name: testing
  hosts: localhost
  tasks:
      - name: debugging from Ansible, facts
        debug:
          var: ansible_facts

      - name: debugging from Ansible, hostvars
        debug:
          var: hostvars

      - name: debugging from Shell exansion
        debug:
          msg: "The IP address is: {{ IP_ADDR }}"

      - name: debugging from Ansible
        debug:
          msg: "The IP address is: {{ lookup('env','PUBLIC_IP') }}"
