---
- name: testing
  hosts: localhost
  become: False
  tasks:
    - name: debugging, node_1
      debug:
        msg: "Node 1's IP address is: {{ NODE_1_IP_ADDR }}"

    - name: debugging, node_2
      debug:
        msg: "Node 2's IP address is: {{ NODE_2_IP_ADDR }}"

    - name: debugging, node_3
      debug:
        msg: "Node 3's IP address is: {{ NODE_3_IP_ADDR }}"

    - name: Use ENV VARS to add hosts to inventory group EC2_WEST and individual node groups
      add_host:
        groups: "{{ item.groups }}"
        name: "{{ item.name }}"
      loop:
        - name: "{{ NODE_1_IP_ADDR }}"
          groups:
          - EC2_West
          - Node1
        - name: "{{ NODE_2_IP_ADDR }}"
          groups:
          - EC2_West
          - Node2
        - name: "{{ NODE_3_IP_ADDR }}"
          groups:
          - EC2_West
          - Node3

- name: Test if hosts are responsive
  hosts: EC2_West
  tasks:
    - name: ping
      ping:


- name: Set up Docker Repository
  hosts: EC2_West
  tasks:
    - name: Remove any vestigial docker binaries from the premade image
      dnf:
        state: absent
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine

    - name: Install necessary tools
      dnf:
        state: present
        name:
          - dnf-utils
          - vim
          - bash-completion
          - git
          - python3

    - name: Add Repository to Yum repositories
      yum_repository:
        baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
        description: "Docker Repo"
        enabled: True
        file: "docker-ce"
        name: "Docker"
        gpgcheck: True
        gpgkey: "https://download.docker.com/linux/centos/gpg"
        state: present

- name: Install Docker Engine, Containerd, Docker Compose and Python3 Docker SDK
  hosts: EC2_West
  tasks:
    - name: Dnf install Docker detritus 
      dnf:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Pip3 install Docker detritus
      pip:
        name: docker

- name: Linux postinstall instructions
  hosts: EC2_West
  tasks:
    - name: Usermod, add EC2 user to Docker group
      user:
        append: True
        groups: "docker"
        name: "ec2-user"
        state: present

    - name: Systemctl, enable docker service to start on boot
      service:
        enabled: True
        state: restarted
        name: "{{ item }}"
      loop:
        - docker
        - containerd

- name: Basic user functionality
  hosts: EC2_West
  tasks:
    - name: Add lines into .bashrc
      lineinfile:
        line: "set -o vi"
        path: /home/ec2-user/.bashrc
        state: present
        create: True
        owner: ec2-user
        group: ec2-user
      
    - name: Add lines in bulk into .vimrc
      blockinfile:
        path: /home/ec2-user/.vimrc
        state: present
        create: True
        owner: ec2-user
        group: ec2-user
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        block: |
         set nocompatible
         set incsearch
         set autoindent smartindent
         set hidden
         set ignorecase smartcase
         syntax enable
         set scrolloff=8
         set noswapfile
         set backupdir=~/.vim/backupdir
         set undofile
         set undodir=~/.vim/undodir
         set updatetime=50
         set timeoutlen=1000 ttimeoutlen=0
         filetype plugin on
         autocmd Filetype yaml setlocal ai ts=2 sw=2 et
         set number relativenumber

    - name: add necessary undo/backup dirs to enable functioning vim
      file:
        state: directory
        path: "{{ item }}"
        owner: ec2-user
        group: ec2-user
      loop:
        - "/home/ec2-user/.vim/undodir"
        - "/home/ec2-user/.vim/backupdir"

    - name: Add other members of group to /etc/hosts
      lineinfile:
        line: "{{ item }}"
        path: /etc/hosts
        state: present
      loop:
        - "{{ NODE_1_IP_ADDR_PRIV }} node1"
        - "{{ NODE_2_IP_ADDR_PRIV }} node2"
        - "{{ NODE_3_IP_ADDR_PRIV }} node3"

    - name: Change the EC2 instance hostnames - Part 1
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

    - name: Change the EC2 instance hostnames - Part 2
      replace:
        replace: "{{ item.replace }}"
        regexp: "{{ item.regexp }}"
        path: /etc/hostname
      loop:
        - regexp: "{{ NODE_1_IP_ADDR }}"
          replace: "node1"
        - regexp: "{{ NODE_2_IP_ADDR }}"
          replace: "node2"
        - regexp: "{{ NODE_3_IP_ADDR }}"
          replace: "node3"

    - name: Change the EC2 instance hostnames - Part 3 (no reboot)
      shell:
        cmd: "grep node /etc/hostname | xargs sudo hostname"
      register: janky

    - name: Change the EC2 instance hostnames - Part 4
      service:
        name: NetworkManager
        state: restarted

- name: Create Docker Swarm cluster
  hosts: EC2_West
  tasks:
    - name: Docker Swarm Init on Node 1
      community.docker.docker_swarm:
        state: present
      when: ansible_hostname == "node1"

    - name: Retrieve Swarm info
      community.docker.docker_swarm_info:
      register: swarm
      when: ansible_hostname == "node1"

    - name: debug join token
      debug:
        var: swarm.swarm_facts.JoinTokens.Worker

    - name: debug addr port
      debug:
        var: "{{ NODE_1_ADDR_PRIV }}:2377"

    - name: Join Node 1 swarm
      community.docker.docker_swarm:
        state: join
        join_token: swarm.swarm_facts.JoinTokens.Worker
        remote_addrs: "{{ NODE_1_IP_ADDR_PRIV }}:2377"
      when: ansible_hostname != "node1"
