---
- name: testing
  hosts: localhost
  tasks:
    - name: debugging, node_1
      debug:
        msg: "Node 1's IP address is: {{ NODE_1_IP_ADDR }}"

    - name: debugging, node_2
      debug:
        msg: "Node 2's IP address is: {{ NODE_2_IP_ADDR }}"

    - name: debugging, node_3
      debug:
        msg: "Node 3's IP address is: {{ NODE_3_IP_ADDR }}"

    - name: using newly discovered add_host
      add_host:
        groups: "{{ item.groups }}"
        name: "{{ item.name }}"
      loop:
        - groups: EC2_West
          name: "{{ NODE_1_IP_ADDR }}"
        - groups: EC2_West
          name: "{{ NODE_2_IP_ADDR }}"
        - groups: EC2_West
          name: "{{ NODE_3_IP_ADDR }}"

- name: test if ENV VAR INJECTION worked
  hosts: EC2_West
  tasks:
    - name: ping
      ping:

