---
- name: testing
  hosts: localhost
  tasks:
    - name: debugging, node_1
      debug:
        msg: "Node 1's IP address is: {{ NODE_1_IP_ADDR }}"

    - name: debugging, node_2
      debug:
        msg: "Node 2's IP address is: {{ NODE_2_IP_ADDR }}"

    - name: debugging, node_3
      debug:
        msg: "Node 3's IP address is: {{ NODE_3_IP_ADDR }}"

    - name: testing setting ENV VARS
      shell:
        cmd: "export ANSIBLE_INVENTORY={{ NODE_1_IP_ADDR }}"

- name: test if ENV VAR INJECTION worked
  hosts: localhost
  tasks:
    - name: debugging, facts
      debug:
        var: ansible_facts
    - name: debugging ANSIBLE_INVENTORY
      debug:
        msg: "{{ lookup('env', 'ANSIBLE_INVENTORY') }}"

